### PR TITLE
Remove local copy of chemspax source code

### LINKED ISSUE #22: Remove chemspax folder from source tree
- The 'install/ chemspax' folder in the obelix source tree is now obsolete because chemspax source has been updated in [this pull request](https://github.com/EPiCs-group/chemspax/pull/19).    
- environment.yml also needs to be updated to point to the chemspax github repository instead of the obelix source tree

### PR DESCRIPTION
**Pull request by niketagrawal**
The local copy of chemspax code in `obelix/install/chemspax` is now the same as the main branch of the chemspax GitHub repository. So, the `obelix/install/chemspax` directory is obsolete. chemspax can be installed form the GitHub repository directly.  This eliminates the scope of any manual errors that might pop up while trying to use this local copy as the code here might get out of sync with the chemspax GitHub repository. 

Additionally, this PR includes a comment in the CI workflow regarding running tests on Ubuntu20.04 

Closes #22 

### Summary of code changes
- The directory `obelix/install/chemspax` is deleted
- environment.yml is modified to install chemspax from GitHub repository instead of the local copy
- Add comment in CI workflow file describing the status of testing on Ubuntu 20.04

### CODE REVIEW

**Comment by akalikadien** [comment]
@niketagrawal, I noticed something when running the example. Now that the ChemSpaX folder is not present anymore, line 202 of the run_workflow.py file points at a non-existing folder for getting the substituents from ChemSpaX. Is there any way in which we could point to the installation folder of ChemSpaX in the user's Python environment?

https://github.com/EPiCs-group/obelix/blob/e5996532085f4aa027c5f7171840430e0bb5b4dd/obelix/run_workflow.py#L202

**Comment by akalikadien** [comment]
Tried to fix this in the following way: `path_to_substituents = os.path.join(chemspax.__path__[0], 'chemspax', 'substituents_xyz', 'manually_generated'). However, I see that the substituents_xyz/manually_generated folder does not exist in that location after installation of chemspax. The folders are included as package data in the setup.py of ChemSpaX (https://github.com/EPiCs-group/chemspax/blob/ec3e7ba809e350d6582075ed2463be6785ff924f/setup.py#L29), so not sure what is going wrong here.

**Comment by niketagrawal** [comment]
@akalikadien I added the fix in the branch [test-fix-remove-chemspax](https://github.com/EPiCs-group/obelix/tree/test-fix-remove-chemspax). Can you run `obelix/example_workflow/example_workflow.py` in this branch and check whether the output is correct? 

Code changes done to fix this issue:
- Line 290 in run_chemspax.py `if self.substituent_list == []:` is replaced with `if self.substituent_list.size == 0:` because self.substituent_list is a NumPy array and comparing it directly to an empty list [] is incorrect. Instead, check if the array is empty using the .size attribute of the NumPy array. example_workflow.py also fails on the main branch. This error is not related to removal of chemspax from the source tree.
- setup.py of chemspax does not correctly package the data files. The `include_package_data_files` line should be uncommented.
- Paths pointing to obelix/install/chemspax are replaced with the path where chemspax is installed in conda environment.

**Comment by akalikadien** [comment]
Tested example of workflow on [test-fix-remove-chemspax](https://github.com/EPiCs-group/obelix/tree/test-fix-remove-chemspax) branch and it generates the correct output. Your fix works.

**Comment by niketagrawal** [comment]
> Tested example of workflow on [test-fix-remove-chemspax](https://github.com/EPiCs-group/obelix/tree/test-fix-remove-chemspax) branch and it generates the correct output. Your fix works.

Thanks for the feedback. 
I have opened a pull request in chemspax repository that fixes the packaging of the data files. Can you please review it?
Untill the pull request in chemspax is merged, I will convert this pull request to draft.

**Comment by niketagrawal** [comment]
Changes to fix the packaging of data files in chemspax are merged. The changes in this pull request can be tested on this feature branch.
 
### Test
- Checkout this feature branch and create a conda environment using the environment.yml file and install obelix in development mode using `pip install -e .`
- Run the example workflow in obelix/example_workflow/

**Review by akalikadien — APPROVED** [review]
Tested on a Linux system and the example works now!

**Pull request merged**
